export default interface PlantDetailsUI {
    "id": number,
    "common_name": string,
    "scientific_name": string[],
    "other_name": [],
    "family": string | null,
    "origin": string[],
    "type": string,
    "dimension": string,
    "dimensions": {
      "type": string,
      "min_value": number,
      "max_value": number,
      "unit": string
    },
    "cycle": string,
    "attracts": string[],
    "propagation": string[] | null,
    "hardiness": {"min": string, "max": string},
    "hardiness_location": {"full_url": string, "full_iframe": string},
    "watering": string,
    "depth_water_requirement": [],
    "volume_water_requirement": [],
    "watering_period": string | null,
    "watering_general_benchmark": {"value": string, "unit": string},
    "plant_anatomy": [
      {"part": string, "color": string[]},
      {"part": string, "color": string[]}
    ],
    "sunlight": string[],
    "pruning_month": string[],
    "pruning_count": [],
    "seeds": number,
    "maintenance": string | null,
    "care-guides": string,
    "soil": [],
    "growth_rate": string,
    "drought_tolerant": false,
    "salt_tolerant": false,
    "thorny": false,
    "invasive": false,
    "tropical": false,
    "indoor": false,
    "care_level": string | null,
    "pest_susceptibility": [],
    "pest_susceptibility_api": string,
    "flowers": false,
    "flowering_season": string | null,
    "flower_color": string,
    "cones": false,
    "fruits": true,
    "edible_fruit": true,
    "edible_fruit_taste_profile": string,
    "fruit_nutritional_value": string,
    "fruit_color": [],
    "harvest_season": string,
    "leaf": true,
    "leaf_color": string[],
    "edible_leaf": false,
    "cuisine": true,
    "medicinal": false,
    "poisonous_to_humans": number,
    "poisonous_to_pets": number,
    "description": string,
    "default_image": {
      "license": 4,
      "license_name": string,
      "license_url": string,
      "original_url": string,
      "regular_url": string,
      "medium_url": string,
      "small_url": string,
      "thumbnail": string
    },
    "other_images": string
  };